// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwA_-0QVr-8cX59HRVzG5echxcafiljis',
    appId: '1:545185432539:web:e8fb9f15bc546a80a01dfe',
    messagingSenderId: '545185432539',
    projectId: 'todo-31938',
    authDomain: 'todo-31938.firebaseapp.com',
    storageBucket: 'todo-31938.appspot.com',
    measurementId: 'G-7WNCX25NK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnb9GyKEtSTmJ4-DXMJQGn5WlnphhxBoY',
    appId: '1:545185432539:android:4a28d22f5dcdc83aa01dfe',
    messagingSenderId: '545185432539',
    projectId: 'todo-31938',
    storageBucket: 'todo-31938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlq9nAi5Pgn8O7UNKLS4-_-kM9AQ4Ng_w',
    appId: '1:545185432539:ios:bddf5c6bbacbaae9a01dfe',
    messagingSenderId: '545185432539',
    projectId: 'todo-31938',
    storageBucket: 'todo-31938.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlq9nAi5Pgn8O7UNKLS4-_-kM9AQ4Ng_w',
    appId: '1:545185432539:ios:bddf5c6bbacbaae9a01dfe',
    messagingSenderId: '545185432539',
    projectId: 'todo-31938',
    storageBucket: 'todo-31938.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwA_-0QVr-8cX59HRVzG5echxcafiljis',
    appId: '1:545185432539:web:eae5241d4fdb46f1a01dfe',
    messagingSenderId: '545185432539',
    projectId: 'todo-31938',
    authDomain: 'todo-31938.firebaseapp.com',
    storageBucket: 'todo-31938.appspot.com',
    measurementId: 'G-WF61NV03PF',
  );
}
